### ISSUE TITLE
Example to include topic routes throws error.

### ISSUE THREAD

**Issue by MukulAgrawal** [JustinTArthur/serverwamp#4]
Example to include route throws error. Used a TopicRouteSet() and included a route in the following line
```
@docs_events.route('docs.changes')
```
it throws following error
```
AttributeError: 'TopicsRouter' object has no attribute 'add_topic'
```

**Comment by JustinTArthur** [comment]
Thanks for catching this. I had only been testing with prefix routes. Fixed in master, will be released shortly.
